<?php

use PHPUnit\Framework\TestCase;
use Flou\Path;
use Flou\Image;

class ImageTest extends TestCase {
    public static $base_path;
    public static $processed_path;
    public static $custom_processed_path;

    public static function setUpBeforeClass() {
        $current_dir = dirname(__FILE__);
        self::$base_path = Path::join($current_dir, "fixtures");
        self::$processed_path = Path::join(self::$base_path, "image1.flou.jpg");
        self::$custom_processed_path = Path::join(self::$base_path, "processed_image.jpg");
        self::_cleanup();
    }

    public static function tearDownAfterClass() {
        self::_cleanup();
    }

    public static function _cleanup() {
        if (file_exists(self::$processed_path)) {
            unlink(self::$processed_path);
        }
        if (file_exists(self::$custom_processed_path)) {
            unlink(self::$custom_processed_path);
        }
    }

    public function testLoadWithBasePath() {
        $path = Path::join(self::$base_path, "image1.jpg");
        $image = (new Flou\Image())
            ->setBasePath(self::$base_path)
            ->load("image1.jpg");
        $this->assertEquals($path, $image->getOriginalFilePath());
    }

    public function testLoadFullPath() {
        $path = Path::join(self::$base_path, "image1.jpg");
        $image = (new Flou\Image())->load($path);
        $this->assertEquals($path, $image->getOriginalFilePath());
    }

    public function testProcess() {
        $processed_path = self::$processed_path;
        $this->assertFalse(file_exists($processed_path));

        $image = (new Flou\Image())
            ->setBasePath(self::$base_path)
            ->load("image1.jpg");
        $this->assertEquals($processed_path, $image->getProcessedFilePath());
        $this->assertFalse($image->isProcessed());

        $image->process();
        $this->assertTrue($image->isProcessed());
        $this->assertTrue(file_exists($processed_path));
    }

    public function testCustomProcessedFile() {
        $initial_processed_path = self::$processed_path;
        $custom_processed_path = self::$custom_processed_path;
        $this->assertFalse(file_exists($custom_processed_path));

        $image = (new Flou\Image())
            ->setBasePath(self::$base_path)
            ->load("image1.jpg");
        $this->assertEquals($initial_processed_path, $image->getProcessedFilePath());

        $image->setProcessedFile("processed_image.jpg");
        $image->process();
        $this->assertTrue($image->isProcessed());
        $this->assertEquals($custom_processed_path, $image->getProcessedFilePath());
        $this->assertTrue(file_exists($custom_processed_path));
    }

    public function testForceProcess() {
        $processed_path = self::$processed_path;

        $image = (new Flou\Image())
            ->setBasePath(self::$base_path)
            ->load("image1.jpg")
            ->process();
        $mtime1 = filemtime($processed_path);

        // The image was processed and saved
        $this->assertTrue($image->isProcessed());

        sleep(1);
        $image->process();
        $mtime2 = filemtime($processed_path);

        // The processed image already existed, it was not regenerated
        $this->assertEquals($mtime1, $mtime2);

        sleep(1);
        $image->forceProcess();
        $mtime3 = filemtime($processed_path);

        // The processed image already existed, but it was regenerated by forceProcess
        $this->assertNotEquals($mtime2, $mtime3);
    }

    public function testGetHTML() {
        $image = (new Flou\Image())
            ->setBasePath(self::$base_path)
            ->load("image1.jpg")
            ->process();
        $this->assertTrue($image->isProcessed());

        // Cannot generate HTML without a base_url
        $html = $image->getHTML();
        $this->assertNull($html);

        $html = $image->setBaseUrl("/img")->getHTML("Image Description");
        $container = new SimpleXMLElement($html);
        $this->assertEquals("flou-container", $container['class']);
        $this->assertEquals(1, count($container->img));
        $this->assertEquals("flou-image", $container->img['class']);
        $this->assertEquals("Image Description", $container->img['alt']);
    }
}
