name: tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  phpunit:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1']
        glide: ['1.*', '2.*']

    name: P${{ matrix.php }} G${{ matrix.glide }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.glide }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.php }}-${{ matrix.glide }}-composer-

    - name: Install dependencies
      run: |
        composer require "league/glide:${{ matrix.glide }}" --no-interaction --no-update
        composer install --prefer-dist --no-interaction --no-plugins

    - name: Run test suite
      run: php vendor/bin/phpunit
